# --- Site basics ---
title: ""
description: "Southern Ocean Sea Ice Mass Balance Assessment"
url: "https://so-simba.github.io"
baseurl: ""

# --- Theme ---
theme: jekyll-theme-minimal

# --- Navigation (top links) ---
header_pages:
  - index.md
  - team.md
  - work.md

# --- Author / Org info ---
author:
  name: "Robert Ricker & SO-SIMBA Team"
  email: "rori@norceresearch.no"

# --- Social links ---
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/so-simba" }

# --- Build settings ---
markdown: kramdown
permalink: pretty
